### ISSUE TITLE
发现一个bug，设置了默认的省市区县之后，当不滚动选择，直接选择默认的，区县显示为默认省市下面排的第一个，而非显示的那个。

### ISSUE THREAD

**Issue by love-311** [crazyandcoder/citypicker#10]
是个比较小的问题，希望作者能够及时修复。

**Comment by crazyandcoder** [comment]
已修复：https://github.com/crazyandcoder/citypicker

**Comment by love-311** [comment]
感谢你的及时修复，我也阅读了你的源码，觉得应该开发更多的属性给开发者，比如title的字体的颜色，确认按钮与取消按钮等字体的大小，title的高度等，这样能够更方便开发者定制，希望作者能给予改进。最后感谢作者的分享。

**Comment by crazyandcoder** [comment]
谢谢你的建议，我会一一参考的！

**Comment by f262866551** [comment]
非常感谢能出这个开源组件，我想问下如果地址过长有什么办法能让item换行呢？谢谢
