### ISSUE TITLE
三级城市选择没有提供数据返回处理

### ISSUE THREAD

**Issue by starlxing** [crazyandcoder/citypicker#100]
三级选择完成之后就只是弹出了一个toast，并没有给出可用的处理数据的接口

**Comment by crazyandcoder** [comment]
@starlxing  下个版本加上

**Comment by crazyandcoder** [comment]
@starlxing   已发布新版本，提供该实现方式，具体请查看 [ 三级城市列表 ](https://github.com/crazyandcoder/citypicker/wiki/%E6%A0%B7%E5%BC%8F%E4%B8%89%EF%BC%88%E7%9C%81%E5%B8%82%E5%8C%BA%E4%B8%89%E7%BA%A7%E5%88%97%E8%A1%A8%EF%BC%89)
