### ISSUE TITLE
大佬 比较紧急的问题

### ISSUE THREAD

**Issue by 179098051** [crazyandcoder/citypicker#103]
我在dialog上弹出这个选择器的时候，它会显示在dialog的下层，这样我就要把dialog取消了之后才能点击选择器，要怎样才能把它放到dialog的上层呢？

**Comment by crazyandcoder** [comment]
首先这个选择器就是一个弹出view，对话框也是，两者放在一起不觉得奇怪么？

你把代码贴出来我看看。
