### ISSUE TITLE
如果直接饮用提供能设置数据源的与方法就好了

### ISSUE THREAD

**Issue by songzhili** [crazyandcoder/citypicker#104]
如果直接饮用提供能设置数据源的与方法就好了

**Comment by woqidaideshi** [comment]
但是怎么设置呢？

**Comment by crazyandcoder** [comment]
直接替换我的本地json数据就行了，但是格式得按照我提供的样本格式。[本地json数据](https://github.com/crazyandcoder/citypicker/blob/master/citypickerview/src/main/assets/china_city_data.json)

**Comment by crazyandcoder** [comment]
自定义数据源功能已添加，请查看最新v5.0.0版本的使用说明：[自定义数据源](https://github.com/crazyandcoder/citypicker/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0)
