### ISSUE TITLE
二级联动数据源问题 直辖市二级多个重复直辖市名字而没有显示区

### ISSUE THREAD

**Issue by tosslife** [crazyandcoder/citypicker#105]
设置CityConfig.WheelType.PRO_CITY 二级联动的时候
对于直辖市 显示有问题 比如 北京市 然后二级里北京市多个，却并未到区
这种不太符合显示目的了
其实楼主可以试试开放设置数据源
虽然您说可以替换assets下json文件，但是编辑器会检查assets下文件是不是xml
无法做到替换，又不可以改名字

**Comment by crazyandcoder** [comment]
@tosslife   感谢提出宝贵意见！
1、出现多个北京市的问题，下个版本会优化
2、开放设置数据源的源跟我写这个开源库的目的是相反的，原本的打算就是不需要你们自己设置数据源，如果想要自己设置的话，完全可以使用其他的滚轮开源库。如果我开放的话就相当于提供了一个滚轮控件而已，没有必要再写城市库的。

**Comment by xucoolmeng** [comment]
大神  你好 请问预计什么时候 会修复二级联动 直辖市显示问题

**Comment by qq380791741** [comment]
快点修复直辖市重复的问题啊 。

**Comment by crazyandcoder** [comment]
@qq380791741 直辖市重复是因为你设置了市区循环的属性，改成false即可避免出现重复了
