### ISSUE TITLE
pinyin4j的jar包和本地工程冲突了

### ISSUE THREAD

**Issue by ysheaven** [crazyandcoder/citypicker#108]
考虑一下不要使用jar包方式，直接引用 compile 'com.belerweb:pinyin4j:2.5.1'

**Comment by joefei** [comment]
是啊,我也遇到这个问题了

**Comment by zhongweitian** [comment]
> 考虑一下不要使用jar包方式，直接引用 compile 'com.belerweb:pinyin4j:2.5.1'
    implementation 'com.belerweb:pinyin4j:2.5.1'
    //地区选择器
    implementation 'liji.library.dev:citypickerview:3.1.13'
    api('liji.library.dev:citypickerview:3.1.13'){
        exclude group: 'com.belerweb'
    }
这样还是没啥用，还是报文件重复定义
Multiple dex files define Lcom/hp/hpl/sparta/xpath/Visitor;

**Comment by zhongweitian** [comment]
> > 考虑一下不要使用jar包方式，直接引用 compile 'com.belerweb:pinyin4j:2.5.1'
> > implementation 'com.belerweb:pinyin4j:2.5.1'
> > //地区选择器
> > implementation 'liji.library.dev:citypickerview:3.1.13'
> > api('liji.library.dev:citypickerview:3.1.13'){
> > exclude group: 'com.belerweb'
> > }
> > 这样还是没啥用，还是报文件重复定义
> > Multiple dex files define Lcom/hp/hpl/sparta/xpath/Visitor;

做了下面 两种尝试
1）删除了引入的pinyin4j的jar包，用这个库的，运行时，其他用到pinyin4j的地方出现null错误
2）留下导入的pinyin4j包，删除这个库的pinyin4j，运行暂时没有发现问题
