### ISSUE TITLE
区的滚轮，不滚动的话取的是第一个

### ISSUE THREAD

**Issue by BestSingerInSiHui** [crazyandcoder/citypicker#11]
我用的0.5.0版本
省和市的都没问题
区的话，如果我是有5个区

                 1
                 2
                 3
___________4___
省    市      5
_______________

我设了默认为5，如果我不滚动的话，直接点确定，拿回来的就是1

**Comment by crazyandcoder** [comment]
@BestSingerInSiHui 这个问题在最新版本已经修复了
