### ISSUE TITLE
台湾地区没有台北市

### ISSUE THREAD

**Issue by Karl9452** [crazyandcoder/citypicker#111]
台湾地区没有台北市,希望麻烦作者能尽快更新下，客户是台湾的

**Comment by Karl9452** [comment]
台北市
12区：内湖区、南港区、中正区、万华区、大同区、中山区、松山区、大安区、信义区、文山区、士林区、北投区

我在百度百科查到的，其他的市都是对的。
我本地引用您的代码已经把城市数据的json文件更新了，经测试可以使用。

**Comment by crazyandcoder** [comment]
多谢反馈，尽快修复该问题。
