### ISSUE TITLE
为什么一级城市列表只出现C跟#标签

### ISSUE THREAD

**Issue by zhongweitian** [crazyandcoder/citypicker#113]
![_20180703205526](https://user-images.githubusercontent.com/36120506/42221122-9ba6d35a-7f03-11e8-8d13-e6de69c81ffe.png)

**Comment by crazyandcoder** [comment]
数据解析失败导致的。

**Comment by luyun181** [comment]
这个问题应该怎么解决呢？

**Comment by ToxicR** [comment]
同问怎样解决

**Comment by erpang12345** [comment]
怎么解决呢

**Comment by crazyandcoder** [comment]
请留下你们的机型

**Comment by luyun181** [comment]
小米5x显示如上问题，是pinyinUtils的错误吗？长沙，重庆，长春是写死的就有？还有，为什么要写死这三个数据？是因为重庆是多音字吗？

**Comment by chenqi97** [comment]
我也出现了这个问题，虚拟机和小米五上都这样，不知道该怎么解决呢？
