### ISSUE TITLE
使用时发现的一点小问题

### ISSUE THREAD

**Issue by AnJiuZhe** [crazyandcoder/citypicker#118]
1.标题等颜色设置希望支持int类型,这样直接从color.xml获取颜色方便些.
2.输入法软键盘弹出的时候,点击button显示城市选择列表,界面被输入法覆盖,输入法软键盘没有隐藏.
目前就这些了,希望大佬有空可以优化下.^_^

**Comment by crazyandcoder** [comment]
非常感谢！
