### ISSUE TITLE
东莞市，中山市的ID一样，问题比较严重紧急

### ISSUE THREAD

**Issue by yangzhanlong** [crazyandcoder/citypicker#124]
东莞市，中山市的ID重复，不知道其他还有没有这种情况的

**Comment by crazyandcoder** [comment]
东莞市id: 441900
中山市id: 442000

怎么会一样？

可以参考数据源：
https://github.com/crazyandcoder/citypicker/blob/master/citypickerview/src/main/assets/china_city_data.json
