### ISSUE TITLE
有没有设置自定义数据源的方法？

### ISSUE THREAD

**Issue by wengeqiua** [crazyandcoder/citypicker#126]
想问有没有只改数据源的方法？想使用自己的数据。

**Comment by crazyandcoder** [comment]
没有提供相关方法

**Comment by crazyandcoder** [comment]
自定义数据源功能已添加，请查看最新v5.0.0版本的使用说明：[自定义数据源](https://github.com/crazyandcoder/citypicker/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0)
