### ISSUE TITLE
急，没有苏州工业园区

### ISSUE THREAD

**Issue by songzhonghua** [crazyandcoder/citypicker#127]
大神，没有苏州工业园区，项目还用了你们的控件，已经上线了。结果有人投诉找不到自己所属的区域，而且选的是社保缴纳地区，不能乱选。园区与市区有很大不同，麻烦帮忙加一个，苏州市下属的区。
工业园区成了有二十年了。

**Comment by songzhonghua** [comment]
大佬 大神，帮帮忙啊

**Comment by crazyandcoder** [comment]
不好意思，这是以前我在国家统计局上面爬下来的数据，可能有点落后了。

我目前不大方便修改，你可以自己修改源码，然后价加个工业园区，在目录下面：
[https://github.com/crazyandcoder/citypicker/blob/master/citypickerview/src/main/assets/china_city_data.json](https://github.com/crazyandcoder/citypicker/blob/master/citypickerview/src/main/assets/china_city_data.json)

**Comment by crazyandcoder** [comment]
或者等周末了我抽空改下数据，谢谢！

**Comment by crazyandcoder** [comment]
@songzhonghua

**Comment by songzhonghua** [comment]
好的，谢谢大佬，非常感谢了。

**Comment by crazyandcoder** [comment]
你那边要是不急的话就等我弄好通知你，急的话直接改下源码。

**Comment by songzhonghua** [comment]
大佬，你弄好了通知我吧，我不是安卓开发，搞不清怎么弄。。。只会简单的打打包。
新安卓程序员还要好几天才能到位o(╥﹏╥)o
非常非常感谢！
好人一生平安~

**Comment by crazyandcoder** [comment]
好的。预计本周末给你解决掉

**Comment by crazyandcoder** [comment]
我在国家网站上面没有查到关于工业园区的数据。

最新数据源已经更新到201812月的，请使用最新版本

**Comment by songzhonghua** [comment]
好的，谢谢
