### ISSUE TITLE
建议支持日期、时间选择

### ISSUE THREAD

**Issue by Wesley254619** [crazyandcoder/citypicker#128]
很多时候设计都是以 iOS 的风格来做的，项目中有各种需要用到选择器的地方，比如 时间、日期、地址...等等。要求风格要一样，但这个目前只支持地址选择，要想实现日期、时间选择，又要另外在导入一个库，就不是很方便了，所以建议支持 日期、时间

**Comment by crazyandcoder** [comment]
多谢建议。日后可以考虑新增类似的需求。
