### ISSUE TITLE
能否加上自定义数据源功能？

### ISSUE THREAD

**Issue by wangchunleioo** [crazyandcoder/citypicker#130]
公司传地址都是用ID传的 大佬的选择器很好用 但是数据不同 请问后期能否加入自定义数据源功能？

**Comment by crazyandcoder** [comment]
非常感谢，已经在考虑加入自定义数据源，等待后期版本

**Comment by JohnFirst** [comment]
这个功能期待author增添此功能，后期关注！

**Comment by crazyandcoder** [comment]
@JohnFirst  请耐心等待，已经在考虑加入自定义数据了。后期版本会开放。
