### ISSUE TITLE
希望作者新增自定义数据源功能

### ISSUE THREAD

**Issue by leileiChenGentleman** [crazyandcoder/citypicker#134]
项目需求不同，可能不止从本地获取数据源

**Comment by crazyandcoder** [comment]
自定义数据源功能已添加，请查看最新v5.0.0版本的使用说明：[自定义数据源](https://github.com/crazyandcoder/citypicker/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90%E5%8A%9F%E8%83%BD%E5%AE%9E%E7%8E%B0)
