### ISSUE TITLE
这个是你以前的github吗?

### ISSUE THREAD

**Issue by qiuwenxin** [crazyandcoder/citypicker#137]
https://github.com/outhlen/citypickerview

**Comment by crazyandcoder** [comment]
不是





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by crazyandcoder** [comment]
我刚看了一下他的github，他应该是把我的仓库copy过去的。感谢提醒😁





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by qiuwenxin** [comment]
好的  还有一个就是我的<application  android:theme=""  >与你的theme冲突了  导致依赖不上去后面是把你的library下下来放到项目中改成我自己的theme才能用的,这是一个问题 我跟你反馈一下 看看能否改善一下!!!!
