### ISSUE TITLE
弹出选择器软键盘

### ISSUE THREAD

**Issue by JayGengi** [crazyandcoder/citypicker#139]
弹出选择器没有关闭已有的软键盘。项目用的地方多，每次弹出之前先手动关闭软键盘实在不友好

**Comment by crazyandcoder** [comment]
这需要你自己实现的，在弹出选择器之前先关闭自己的软键盘。

**Comment by JayGengi** [comment]
嗯嗯，目前是这样的...

**Comment by JayGengi** [comment]
比如时间选择器，日历等第三方控件启动时都有处理，不过也不麻烦，还是很感觉大佬开源地区选择器<手动膜拜>

**Comment by crazyandcoder** [comment]
非常感谢使用，欢迎提出更多建议~
