### ISSUE TITLE
自定义属性太过普通，非常容易导致与其他库的自定义属性重合导致编译失败

### ISSUE THREAD

**Issue by love-311** [crazyandcoder/citypicker#14]
![image](https://cloud.githubusercontent.com/assets/19263806/21001510/a9fae2cc-bd5b-11e6-9456-f6d078c780ab.png)
今天我就遇到使用本库与另外一个库都定义了一个相同的自定义属性导致编译失败的情况 
<declare-styleable name="CityPickerView">
        <attr name="title_background" format="color"></attr>
        <attr name="text_confirm_color" format="color"></attr>
        <attr name="text_cancel_color" format="color"></attr>
        <attr name="wheel_color" format="color"></attr>
        <attr name="wheel_text_color" format="color"></attr>
        <attr name="wheel_text_size" format="dimension"></attr>
        <attr name="title_text_size" format="dimension"></attr>
        <attr name="title_action_size" format="dimension"></attr>
    </declare-styleable>
我这里遇到的情况是title_background与另外一个库相同了，希望作者可以尽快的修复就不用我自己改了，哈哈。。

**Comment by crazyandcoder** [comment]
你很幸运，一般人都遇不到~

**Comment by hao8023** [comment]
请问怎么修改的  ？ 我也是这个问题

**Comment by crazyandcoder** [comment]
@hao8023 正在修改中...

**Comment by love-311** [comment]
楼主加油么么哒。。😄

**Comment by crazyandcoder** [comment]
@love-311  @hao8023  问题已修复，请使用最新版本0.8.0

**Comment by love-311** [comment]
感谢感谢。。😁

**Comment by crazyandcoder** [comment]
@love-311   马马达！
