### ISSUE TITLE
香港地区有id重复

### ISSUE THREAD

**Issue by SiegeLeo** [crazyandcoder/citypicker#140]
香港地区有两个地方的ID都是 810304

**Comment by SiegeLeo** [comment]
全香港主要分为四部分：香港岛四区（港岛区）、九龙半岛五区、新界东四区，新界西五区。每部分皆由数个区域组成，如果按行政分区计算，全港共有18个行政区。
港岛区主要由4个行政分区组成：中西区、湾仔区、东区及南区。
九龙半岛分为5个行政分区：九龙城区、观塘区、深水埗区、黄大仙区及油尖旺区，黄大仙及观塘区，我们称为东九龙（九龙东），油尖旺区、深水埗及九龙城，我们称为西九龙（九龙西）。
新界就是指从九龙界限街以北至深圳河以南之间的土地，以地理上划分，新界可分西区、北区及东区，总面积超过740平方公里。
新界西区包括荃湾区、屯门区、元朗区、葵青区。新界东区就是在新界以东的地区，包括北区、大埔区、沙田区及西贡区。

**Comment by crazyandcoder** [comment]
感谢反馈！
1. 第一个问题已经解决。
2. 第二个问题，请问你的数据来源在哪里？方便贴个链接么？

谢谢！

**Comment by SiegeLeo** [comment]
维基百科和很多文章都有写
https://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF#%E8%A1%8C%E6%94%BF%E5%88%86%E5%8D%80
