### ISSUE TITLE
样式问题，最新版

### ISSUE THREAD

**Issue by lishiyu1810** [crazyandcoder/citypicker#141]
![QQ图片20190314120014](https://user-images.githubusercontent.com/11992062/54330458-c18bbf80-4650-11e9-9870-6a8b11fa970d.png)

我自定义item的时候 没有数据的item，没办法设置背景

还有中间那个黑线不知道是什么情况

使用模拟机的时候   这个弹出框为什么会在那个返回键、home键下面呢？

求解答...

**Comment by crazyandcoder** [comment]
代码贴出来看看呢

**Comment by lishiyu1810** [comment]
> 代码贴出来看看呢

CityConfig cityConfig = new CityConfig.Builder()
                .title("选择城市")//标题
                .titleTextSize(18)//标题文字大小
                .titleTextColor("#333333")//标题文字颜  色
                .titleBackgroundColor("#f5f5f5")//标题栏背景色
                .confirTextColor("#333333")//确认按钮文字颜色
                .confirmText("确定")//确认按钮文字
                .confirmTextSize(16)//确认按钮文字大小
                .cancelTextColor("#333333")//取消按钮文字颜色
                .cancelText("取消")//取消按钮文字
                .cancelTextSize(16)//取消按钮文字大小
                .setCityWheelType(CityConfig.WheelType.PRO_CITY)//显示类，只显示省份一级，显示省市两级还是显示省市区三级
                .showBackground(true)//是否显示半透明背景
                .visibleItemsCount(5)//显示item的数量
//                .province("浙江省")//默认显示的省份
//                .city("杭州市")//默认显示省份下面的城市
//                .district("滨江区")//默认显示省市下面的区县数据
                .provinceCyclic(false)//省份滚轮是否可以循环滚动
                .cityCyclic(false)//城市滚轮是否可以循环滚动
                .districtCyclic(false)//区县滚轮是否循环滚动
                .setCustomItemLayout(R.layout.item_city)//自定义item的布局
                .setCustomItemTextViewId(R.id.item_city_name_tv)//自定义item布局里面的textViewid
                .drawShadows(false)//滚轮不显示模糊效果
                .setLineColor("#ff5662")//中间横线的颜色
                .setLineHeigh(1)//中间横线的高度
                .setShowGAT(true)//是否显示港澳台数据，默认不显示
                .build();

//设置自定义的属性配置
mPicker.setConfig(cityConfig);

如果设置可以循环就会变成下面这样子
![QQ图片20190314173704](https://user-images.githubusercontent.com/11992062/54346330-d9c70300-467f-11e9-8227-bb515d590686.png)

**Comment by crazyandcoder** [comment]
自定义布局文件代码也贴一下

**Comment by lishiyu1810** [comment]
> 自定义布局文件代码也贴一下
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:id="@+id/item_city_name_tv"
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:background="@color/page_white_bg"
        android:gravity="center"
        android:text="hello"
        android:textSize="18sp"/>
</LinearLayout>

就是复制的你那个 只是改了一个背景颜色

**Comment by crazyandcoder** [comment]
<img width="376" alt="屏幕快照 2019-03-14 下午6 21 11" src="https://user-images.githubusercontent.com/12810244/54349366-15fd6200-4686-11e9-8ecd-a883aecf4ab5.png">

这个使用你的代码写的，我这边没有出现你这种情况，你再用真机试试看

**Comment by lishiyu1810** [comment]
> <img alt="屏幕快照 2019-03-14 下午6 21 11" width="376" src="https://user-images.githubusercontent.com/12810244/54349366-15fd6200-4686-11e9-8ecd-a883aecf4ab5.png">
> 
> 这个使用你的代码写的，我这边没有出现你这种情况，你再用真机试试看

好的，麻烦你了。谢谢
