### ISSUE TITLE
四级联动，需求想添加四级，添加乡镇，需要怎么设置呢？

### ISSUE THREAD

**Issue by weilei131** [crazyandcoder/citypicker#147]
四级联动，需求想添加四级，添加乡镇，需要怎么设置呢？

**Comment by crazyandcoder** [comment]
不支持这需求





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by as11051105** [comment]
同问，四级，且自有数据怎么弄？

**Comment by crazyandcoder** [comment]
在我的布局里面再加上一个滚轮，然后重新解析数据，设置数据源
