### ISSUE TITLE
背景色修改

### ISSUE THREAD

**Issue by yishangfei** [crazyandcoder/citypicker#154]
![image](https://user-images.githubusercontent.com/15099278/62281276-0e492900-b480-11e9-8153-3ce6eb94109d.png)

我找到修改的只有setCustomItemLayout
![image](https://user-images.githubusercontent.com/15099278/62281302-1acd8180-b480-11e9-88f8-d182f11b1969.png)
这样设置只有一行是白的  如果整个背景设置白色  除了修改源码没别的办法吗

**Comment by crazyandcoder** [comment]
除了设置以上的属性之外，另外再加一个属性：
showBackground(false) 即可。

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/62339443-96760f80-b50e-11e9-9cbb-739beb8d5f05.png)
老哥na那边上模糊是设置什么呀

**Comment by crazyandcoder** [comment]
上面灰色其实是阴影造成的，设置这个属性就是去掉阴影





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by yishangfei** [comment]
那我这种情况只能二选一了吗  不能做出我这种ui图的效果吗

**Comment by crazyandcoder** [comment]
你是要白色的还是要蓝色的UI？

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/62349151-79066d00-b531-11e9-9e10-cebafe02cfc8.png)
这是设计图
![image](https://user-images.githubusercontent.com/15099278/62349172-8c193d00-b531-11e9-9194-44e2e3448116.png)
这是我做出来的  想选择的上下有一点点模糊

**Comment by crazyandcoder** [comment]
如果一定要实现你这种UI的话，只能修改源码，定制





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
