### ISSUE TITLE
三级城市列表样式不能更改

### ISSUE THREAD

**Issue by yrjwcharm** [crazyandcoder/citypicker#158]
![image](https://user-images.githubusercontent.com/34397383/66295154-3d1aca00-e91d-11e9-9984-ebb1527e84aa.png)

**Comment by yrjwcharm** [comment]
上边的titlebar 的背景颜色改不了

**Comment by crazyandcoder** [comment]
@yrjwcharm  目前暂时不支持自定义修改属性，可以下载源码直接修改。

**Comment by yrjwcharm** [comment]
@crazyandcoder You are the  best!!!

**Comment by crazyandcoder** [comment]
@yrjwcharm you 2! ~~~
