### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by JiangShuLiang** [crazyandcoder/citypicker#16]
首先感谢你做的这个滚动选择器，真的很棒，我直接拿到我项目里就可以用了，非常的感谢！！！

然后提两个小建议：
1，建议自定义titleColor，如下图，如果设置了titleBackgroundColor，那么黑色的title就不美观了
![_20161227102005](https://cloud.githubusercontent.com/assets/20485764/21488728/10211b0e-cc1e-11e6-8bf5-24a97bdd92f1.png)

2，建议增加一个在空白处点击让选择器消失的功能：就是用户点击下图红框区域能让选择器消失
![_20161227102151](https://cloud.githubusercontent.com/assets/20485764/21488793/92a8f38a-cc1e-11e6-8768-d8d9f3982f91.png)

最后的最后，还是很感谢作者！

**Comment by crazyandcoder** [comment]
感谢使用，你提的建议不错，下个版本会增加响应属性。

**Comment by JiangShuLiang** [comment]
想问一下，点击取消按钮触发的方法是哪个？我想在按下取消动作里加些代码

**Comment by crazyandcoder** [comment]
源码很简单，建议看一下源码就知道了。
