### ISSUE TITLE
台湾数据是不是太粗心了，，怎么连台北都没有。不完整啊

### ISSUE THREAD

**Issue by huanghaoming** [crazyandcoder/citypicker#163]

**Comment by yangqb** [comment]
你的台北数据弄到了吗

**Comment by crazyandcoder** [comment]
我这边在国家统计局上面获取的省市区数据。他上面没有包含港澳台的，我是在wiki上面搜的港澳台数据，如果你那边有详细的数据，可以提供给我，我来更新一下，谢谢～

**Comment by huanghaoming** [comment]
哈哈，可能我语气有点过了，我其实也没有数据，不然也不会找你了，狗头



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: crazyandcoder <notifications@github.com&gt;
发送时间: 2020年1月2日 11:36
收件人: crazyandcoder/citypicker <citypicker@noreply.github.com&gt;
抄送: huanghaoming <1585685035@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[crazyandcoder/citypicker] 台湾数据是不是太粗心了，，怎么连台北都没有。不完整啊 (#163)

**Comment by yangqb** [comment]
可以

---原始邮件---
发件人: "crazyandcoder"<notifications@github.com&gt;
发送时间: 2020年1月2日(周四) 中午11:36
收件人: "crazyandcoder/citypicker"<citypicker@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"yangqb"<694125155@qq.com&gt;;
主题: Re: [crazyandcoder/citypicker] 台湾数据是不是太粗心了，，怎么连台北都没有。不完整啊 (#163)



我这边在国家统计局上面获取的省市区数据。他上面没有包含港澳台的，我是在wiki上面搜的港澳台数据，如果你那边有详细的数据，可以提供给我，我来更新一下，谢谢～

**Comment by yangqb** [comment]
已经发给你附件了------------------ 原始邮件 ------------------
发件人: "crazyandcoder"<notifications@github.com>
发送时间: 2020年1月2日(星期四) 中午11:35
收件人: "crazyandcoder/citypicker"<citypicker@noreply.github.com>;
抄送: "yangqb"<694125155@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [crazyandcoder/citypicker] 台湾数据是不是太粗心了，，怎么连台北都没有。不完整啊 (#163)



我这边在国家统计局上面获取的省市区数据。他上面没有包含港澳台的，我是在wiki上面搜的港澳台数据，如果你那边有详细的数据，可以提供给我，我来更新一下，谢谢～
 
&mdash;
