### ISSUE TITLE
CustomCityPicker怎么设置默认数据呢？

### ISSUE THREAD

**Issue by dzxyzhanglin** [crazyandcoder/citypicker#167]
CustomCityPicker怎么设置默认数据呢？

**Comment by crazyandcoder** [comment]
设置数据源的话可以参考demo：[自定义数据源](https://github.com/crazyandcoder/citypicker/wiki/%E6%A0%B7%E5%BC%8F%E4%B8%80%EF%BC%88%E4%BB%BFiOS%E6%BB%9A%E8%BD%AE%E5%AE%9E%E7%8E%B0%EF%BC%89%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E6%BA%90)

**Comment by dzxyzhanglin** [comment]
这个我已经看到了。
我想问的是：在回显的时候， 我需要设置默认选中。但是没有看到这个api。

**Comment by crazyandcoder** [comment]
@dzxyzhanglin  这个暂时没有提供默认选中的API，可以提供个思路，仅供参考：
1.在你的数据源中遍历你需要默认显示的数据，获取到他的index
2.使用WheelView的setCurrentItem(index)这个方法设定到当前城市即可。
