### ISSUE TITLE
关于弹出背景透明的一个建议

### ISSUE THREAD

**Issue by JiangShuLiang** [crazyandcoder/citypicker#17]
作者你的方案应该是一个activity从上往下进入，除了选择器以外的地方背景都设置成带透明度的。但是这样子给用户的感觉会很生硬，因为用户可以很容易察觉到像我说的这个过程。

建议改善的方案是：
在弹出选择器的时候设置一下window的透明度
WindowManager.LayoutParams lp = getWindow().getAttributes();
        lp.alpha = 0.5f;
        getWindow().setAttributes(lp);

然后再在监听方法里恢复window的透明度
WindowManager.LayoutParams lp = getWindow().getAttributes();
        lp.alpha = 1f;
        getWindow().setAttributes(lp);

这样子效果就很自然，但是同时有一个bug，就是监听方法应该是对应按下确定按钮的动作，而用户要是按下取消按钮返回后，整个window就还是透明的。所以想问一下作者，能否提供一下监听取消按钮的接口，这样子就能完善这个小bug了。

**Comment by crazyandcoder** [comment]
感谢你的使用，不过我用的是popwindow而不是activity，所以不存在你说的用户体验，源码很简单，建议你稍微看下。
