### ISSUE TITLE
行政区划数据能及时更新么？山东济南下面的行政区划过时了。请尽快更新，谢谢

### ISSUE THREAD

**Issue by MasterMaru** [crazyandcoder/citypicker#175]
如题。

**Comment by crazyandcoder** [comment]
能否提供最新的数据？

**Comment by MasterMaru** [comment]
http://www.mca.gov.cn/article/sj/xzqh/2019/2019/201912251506.html

**Comment by crazyandcoder** [comment]
已修复，使用5.2.1版本

**Comment by MasterMaru** [comment]
老哥，我感觉你直接套用民政部发布的行政区划数据就行。你这样不整体更新，靠使用者反馈问题，一点一点修改，感觉不太合适啊。济南下边数据是更新了，多了莱芜区和钢城区，但是市一级应该删除莱芜市。民政部每年都发布新的行政区划数据，你可以持续关注一下，持续更新。http://www.mca.gov.cn/article/sj/xzqh/2019/

**Comment by crazyandcoder** [comment]
@MasterMaru   感谢反馈，我这用的是2018年的数据，2019年的还没更新上去，只是按照你的要求，更改你那部分的数据的。等抽空，我把它整体替换掉，近阶段有点忙，抽不开身～抱歉

**Comment by xiangyuecn** [comment]
可以参考 #228 更新获取到最新版的省市区数据

建议开发当天转换得到新文件，这样就能使用到最新版本数据，所使用的数据源是我的开源库 https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov ，基本上月更，除了省市区乡镇四级区划外，还有坐标边界数据。欢迎用 #228 的代码在线转成china_city_data.json
