### ISSUE TITLE
我引用后为啥报空指针

### ISSUE THREAD

**Issue by lzrlove** [crazyandcoder/citypicker#177]
![image](https://user-images.githubusercontent.com/52810101/76047081-aec67500-5f9c-11ea-81d9-2d9eb0d554e6.png)
执行CityParseHelper里面的 for (int j = 0; j < cityList.size(); j++) 就空指针了

**Comment by crazyandcoder** [comment]
有进行初始化吗？需要先初始化获取城市数据
