### ISSUE TITLE
请问能否写一个取消按钮的监听事件

### ISSUE THREAD

**Issue by JiangShuLiang** [crazyandcoder/citypicker#18]
是这样的：
我想通过以下这种方式设置背景透明度
  WindowManager.LayoutParams lp = getWindow().getAttributes();
        lp.alpha = 0.5f;
        getWindow().setAttributes(lp);

然后在确定按钮的监听事件里恢复透明度：
  WindowManager.LayoutParams lp = getWindow().getAttributes();
        lp.alpha = 1f;
        getWindow().setAttributes(lp);

但是如果用户一旦按了取消按钮，那么整个界面都还是透明的状态，所以想希望作者能不能提供一个取消按钮的监听事件，我好在里面恢复背景透明度

先感谢一下了！！！！！

**Comment by crazyandcoder** [comment]
我已经提供了设置透明度的属性：backgroundPop（背景，默认为半透明，16位进制颜色代码，带alpha值，如0xa0ffffff），如果再通过其他的方式设置的话不是多此一举吗？

**Comment by JiangShuLiang** [comment]
你的意思我明白，但是你这样做出来的透明背景效果有点生硬，因为用户很明显地就能看出其实就是一个上半部分是透明的页面从下往上进入手机屏幕中。

理想的效果应该是：整个背景先变暗，然后这个你的这个citypicker再出现，这样子效果就很自然

**Comment by crazyandcoder** [comment]
厉害，执着。很多人用到现在只有你提出这个要求，堪比产品经理了，行等下个版本发版，添加这个取消监听给你，就为你一个人开放。

**Comment by JiangShuLiang** [comment]
大写加粗的感谢！！！！！！！！！！！！

**Comment by crazyandcoder** [comment]
妈蛋，这是秒回啊！
