### ISSUE TITLE
作者你好，请问怎么在弹出选择器时设置默认的城市呢？（城市修改时的场景）

### ISSUE THREAD

**Issue by q88qaz** [crazyandcoder/citypicker#181]
作者你好，请问怎么在弹出选择器时设置默认的城市呢？（更新所在城市时的场景）

**Comment by crazyandcoder** [comment]
目前只有仿iOS样式的提供了默认城市的属性。

通过设置以下属性即可：
 .province("浙江省")//默认显示的省份
 .city("杭州市")//默认显示省份下面的城市
 .district("滨江区")//默认显示省市下面的区县数据

如果是其他样式的话，暂时还没提供。
