### ISSUE TITLE
自定义数据源 无法设置默认显示的数据

### ISSUE THREAD

**Issue by zhiziqing** [crazyandcoder/citypicker#194]
自定义数据源，无法设置弹窗显示设置的数据；请问在使用自定义数据源时，如何设置一打开弹窗默认选中的省市县数据？

**Comment by zhuyuyan** [comment]
同问

**Comment by crazyandcoder** [comment]
暂时没有提供该方法设置默认选中城市数据功能

**Comment by zhiziqing** [comment]
这个问题我这边已经改了源码，自定义数据源现在也可以设置默认显示的数据啦 。谢谢~

**Comment by zhuyuyan** [comment]
怎么使用 如何设置？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "crazyandcoder/citypicker"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 上午10:19
收件人:&nbsp;"crazyandcoder/citypicker"<citypicker@noreply.github.com&gt;;
抄送:&nbsp;"小朱"<519994386@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [crazyandcoder/citypicker] 自定义数据源 无法设置默认显示的数据 (#194)





 
这个问题我这边已经改了源码，自定义数据源现在也可以设置默认显示的数据啦 。谢谢~

**Comment by zhiziqing** [comment]
直接使用这个lib
[citypickerview-x.zip](https://github.com/crazyandcoder/citypicker/files/5193110/citypickerview-x.zip)
或者替换这两个文件
[file.zip](https://github.com/crazyandcoder/citypicker/files/5193149/default.zip)

>使用方法和原来一致，仅仅在之前的基础上添加了以下3个方法：
`setDefaultProvince`
`setDefaultCity`
`setDefaultDistrict`

@zhuyuyan
