### ISSUE TITLE
有很多地区数据没有更新,建议使用最新的数据

### ISSUE THREAD

**Issue by XieZhiFa** [crazyandcoder/citypicker#197]
这个是 2020年5月中华人民共和国县以上行政区划代码
http://www.mca.gov.cn/article/sj/xzqh/2020/
建议使用!

**Comment by crazyandcoder** [comment]
@XieZhiFa  非常感谢，请耐心等待最新版本

**Comment by githubPgy** [comment]
这个数据问题比较重要呀

**Comment by qddzcbl** [comment]
还需要耐心等待多久，再不更新就得换别的库了

**Comment by tjn648609716** [comment]
@crazyandcoder 
大佬这里有现成的数据
https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pca-code.json

**Comment by crazyandcoder** [comment]
@XieZhiFa @githubPgy @qddzcbl @tjn648609716 数据问题已更新，请使用最新版本v6.0.0

**Comment by xiangyuecn** [comment]
可以参考 #228 更新获取到最新版的省市区数据

建议开发当天转换得到新文件，这样就能使用到最新版本数据，所使用的数据源是我的开源库 https://github.com/xiangyuecn/AreaCity-JsSpider-StatsGov ，基本上月更，除了省市区乡镇四级区划外，还有坐标边界数据。欢迎用 #228 的代码在线转成china_city_data.json
