### ISSUE TITLE
界面显示问题 名称过长 显示不全

### ISSUE THREAD

**Issue by stone-gao** [crazyandcoder/citypicker#198]
WheelView 模式  例如  彭水苗族土家族自治县  换行显示时有部分字显示不全

**Comment by kailaisi** [comment]
我是使用了自定义的view来显示。
但是我这使用自定义数据源又不支持。
太尴尬了这个情况

**Comment by crazyandcoder** [comment]
已增加自定义数据源自定义item样式的属性，请使用最新版本v5.2.4

**Comment by crazyandcoder** [comment]
@stone-gao WheelView 模式，使用自定义item样式的属性解决你这个问题
