### ISSUE TITLE
自定义选择器能不能设置默认选中 

### ISSUE THREAD

**Issue by thatCbin** [crazyandcoder/citypicker#200]
比如我自定义了    A,B,C 三个数据   然后  弹窗窗口的时候可以设置  默认在 B ,而不是默认在A

**Comment by Dajkwen** [comment]
可以试试将 CustomCityPicker 拷贝一份到自己项目里，在内部调整下逻辑，内部 WheelView 提供了方法，但就是没开放出来

**Comment by Dajkwen** [comment]
@thatCbin 可以试试将 CustomCityPicker 拷贝一份到自己项目里，在内部调整下逻辑，内部 WheelView 提供了方法，但就是没开放出来

**Comment by thatCbin** [comment]
Ok正在尝试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jackwen"<notifications@github.com&gt;; 
发送时间: 2020年11月25日(星期三) 下午4:48
收件人: "crazyandcoder/citypicker"<citypicker@noreply.github.com&gt;; 
抄送: "文"<364743742@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [crazyandcoder/citypicker] 自定义选择器能不能设置默认选中  (#200)





 
可以试试将 CustomCityPicker 拷贝一份到自己项目里，在内部调整下逻辑，内部 WheelView 提供了方法，但就是没开放出来

**Comment by crazyandcoder** [comment]
已增加默认设置选中的属性，请使用最新版本V5.2.4
