### ISSUE TITLE
获取拼音异常

### ISSUE THREAD

**Issue by fgcggg** [crazyandcoder/citypicker#201]
String[] hanzi = PinyinHelper.toHanyuPinyinStringArray('单');
implementation 'com.github.open-android:pinyin4j:2.5.0' 返回正常
implementation 'liji.library.dev:citypickerview:5.2.1'返回null
这2个又不能同时加入工程，如何解决？

**Comment by crazyandcoder** [comment]
已修复，请使用最新版本
