### ISSUE TITLE
有需要最新数据源的可以到这里下载最新的直接替换

### ISSUE THREAD

**Issue by tjn648609716** [crazyandcoder/citypicker#216]
项目地址：
https://github.com/modood/Administrative-divisions-of-China
三级联动地址：
https://github.com/modood/Administrative-divisions-of-China/blob/master/dist/pca-code.json

跟原有数据结构是一样的，适配一下字段名就好

**Comment by crazyandcoder** [comment]
@tjn648609716  v6.0.0 已经使用最新数据源，感谢反馈～
