### ISSUE TITLE
我在使用之余发现了BUG和可以改进之处。写在下面供你参考。也解决了#23的问题。

### ISSUE THREAD

**Issue by IsSwm** [crazyandcoder/citypicker#24]
您好，首先谢谢你分享这个库给我们使用，很方便。
由于写完之后，不知道为什么显示如下错误，导致提交的灰色的，提交不了Issues，所以写到了我的简书里面，可以去简书里面查看。地址》[citypicker的改进的建议，和出现的BUG。](http://www.jianshu.com/p/d110aee34738)  
![错误](https://cloud.githubusercontent.com/assets/22268505/25040730/c6b2c376-213d-11e7-879a-aa47bba76f8f.png)

#23  的问题》点击pop以外，让其消失。@ZhangTengCR7
也可以通过查看 ，[citypicker的改进的建议，和出现的BUG。](http://www.jianshu.com/p/d110aee34738)  解决

**Comment by crazyandcoder** [comment]
牛逼了，谢谢啦，我看看~

**Comment by IsSwm** [comment]
没有，你源码写的比较清晰，我改起来才比较方便。
