### ISSUE TITLE
When i set Options.withMaxResultSize(500,500), the image is so blur, how can i make the picture clear?

### ISSUE THREAD

**Issue by wahyip** [crazyandcoder/citypicker#28]
My image is "1080x1920"..

        UCrop.Options options = new UCrop.Options();
        options.setCompressionQuality(100);
        options.withMaxResultSize(500, 500);
        options.withAspectRatio(4, 3);
        uCrop = uCrop.withOptions(options);

How to capture the biggest wide high for 500*500 images, without changing the definition..

**Comment by crazyandcoder** [comment]
are you kidding me ???? 一脸懵逼中....
