### ISSUE TITLE
服务器获取的数据 要怎么 设置上去呢

### ISSUE THREAD

**Issue by a458167371** [crazyandcoder/citypicker#29]
我们服务器返回的是省市区数据 每一个省市区对应一个id  提交的时候 提交id  我现在的做法就是点击确定的时候  把服务器的数据遍历  和选择的数据做对比 相同 得到对应的省市区的id  但是和ios显示的还是有差别 
有没有方法 直接设置呢

**Comment by crazyandcoder** [comment]
暂时不支持直接设置服务器数据，以后会支持直接设置数据源，不过得按照特定的数据格式进行解析
