### ISSUE TITLE
你好,你这个我下载下来提示找不到CityListSelectActivity类,还有一个属性没有,是怎么回事呢

### ISSUE THREAD

**Issue by Hooks-hu** [crazyandcoder/citypicker#30]
你好,你这个我下载下来提示找不到CityListSelectActivity类,还有一个属性没有,是怎么回事呢

**Comment by crazyandcoder** [comment]
下载下来？是直接下载代码，然后直接导入module的形式导进工程的嘛？

我刚试了一下，直接添加最新的依赖：

compile 'liji.library.dev:citypickerview:1.1.0'//城市列表选择器

然后就可以使用了列表选择器和滚轮选择器了。你可以再试试。

另外，你把error log贴出来给我看看。
