### ISSUE TITLE
添加依赖项目报错

### ISSUE THREAD

**Issue by xiehuiyun** [crazyandcoder/citypicker#32]
![h slqz ei3 raqoy_ 1spy](https://cloud.githubusercontent.com/assets/20488041/26769774/213bd96c-49e4-11e7-985b-07c5b213847e.png)

![ftiwqn_7ss kgh7 4 3xh](https://cloud.githubusercontent.com/assets/20488041/26769793/54612324-49e4-11e7-8bc8-a5fd1cc939a2.png)

**Comment by xiehuiyun** [comment]
我不知道为什么会错。

**Comment by crazyandcoder** [comment]
@xiehuiyun 原因就是我写的代码没有提交，使用依赖的方式是可以的，但是直接引用代码是会报错的，现在已经提交了，你再试试看！
