### ISSUE TITLE
建议增加json和xml数据可以自己配置的功能

### ISSUE THREAD

**Issue by LeonXtp** [crazyandcoder/citypicker#36]
并不总是需要那么多而全的选择的，比如某个商家，它的服务地区有限，那么就只需要在指定的范围内让用户选择地区，并且随着业务的扩张或者其他变更，这些地区并不固定，所以这个数据存在动态变化的特点，并不适合放在assets里面

**Comment by crazyandcoder** [comment]
这个思路是好的~但是我写这个库的原始初衷就是针对于省市区三级联动的，而省市区的数据一般都是固定不变的。现在所要求的动态变化，那么用户可以自己使用WheelView这个控件独立使用，这并适合与全体需求~
