### ISSUE TITLE
根据当前的市，更新区WheelView的信息 的updateAreas（）方法报空指针 是什么原因？

### ISSUE THREAD

**Issue by huanggongyao** [crazyandcoder/citypicker#38]
private void updateAreas() {
        int pCurrent = mViewCity.getCurrentItem();
        mCurrentCityName = mCitisDatasMap.get(mCurrentProviceName)[pCurrent];
        String[] areas = mDistrictDatasMap.get(mCurrentCityName);

        if (areas == null) {
            areas = new String[]{""};
        }

        int districtDefault = -1;
        if (!TextUtils.isEmpty(defaultDistrict) && areas.length > 0) {
            for (int i = 0; i < areas.length; i++) {
                if (areas[i].contains(defaultDistrict)) {
                    districtDefault = i;
                    break;
                }
            }
        }

        ArrayWheelAdapter districtWheel = new ArrayWheelAdapter<String>(context, areas);
        // 设置可见条目数量
        districtWheel.setTextColor(textColor);
        districtWheel.setTextSize(textSize);
        mViewDistrict.setViewAdapter(districtWheel);
        if (-1 != districtDefault) {
            mViewDistrict.setCurrentItem(districtDefault);
            //获取默认设置的区
            mCurrentDistrictName = defaultDistrict;
        } else {
            mViewDistrict.setCurrentItem(0);
            //获取第一个区名称
            if (mDistrictDatasMap != null) {
///////////////////////////////////////////////////////////////////
////////下面一行报空指针
                mCurrentDistrictName = mDistrictDatasMap.get(mCurrentCityName)[0];
/////////////////////////////////////////////////////////////////
            } else {
                mCurrentDistrictName = "";
            }
        }
        districtWheel.setPadding(padding);
//        JLogUtils.D("zipcode key: " + mCurrentProviceName + mCurrentCityName + mCurrentDistrictName);
        //获取第一个区名称
        mCurrentZipCode = mZipcodeDatasMap.get(mCurrentProviceName + mCurrentCityName + mCurrentDistrictName);
    }

**Comment by crazyandcoder** [comment]
请使用最新版本
