### ISSUE TITLE
请问可以做多国语言吗？

### ISSUE THREAD

**Issue by PeterXiaosa** [crazyandcoder/citypicker#39]
省市区的选择器可以做成多国语言吗？在不同语言下我想要将省市区显示成相对应的语言，例如英语，请问应该如何做呢？

**Comment by PeterXiaosa** [comment]
province_data.xml 请问楼主如何将这个文件做成多国语言呢？

**Comment by crazyandcoder** [comment]
在国外用国内的省市区干嘛？没有考虑国外的，做多语言的话，还是得需要一个一个翻译过去的

**Comment by PeterXiaosa** [comment]
请问该如何做呢？翻译倒不是问题

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by crazyandcoder** [comment]
@PeterXiaosa 一个一个对应翻译啊，这有这么蠢的方法了。

**Comment by PeterXiaosa** [comment]
...我也知道需要一个一个对应翻译  我的意思是根据province_data.xml文件翻译英文成另外一个xml文件吗？以及将这个文件放置于何处呢？

**Comment by crazyandcoder** [comment]
@PeterXiaosa   你可以自己生成一个xml文件，然后修改源码里面的文件路径就好了

**Comment by PeterXiaosa** [comment]
十分感谢 我也是这样想的 我准备在源码里判断系统使用语言然后根据具体语言选用不同的xml文件 然后一直在搜如何修改源码 但是还是一直不知道如何修改你的源码... 方便再次指教一下吗？

**Comment by PeterXiaosa** [comment]
我刚刚已经解决了问题，我将你的.java源码copy到我项目新建的一个.java里，然后通过系统语言判断选用不同的xml文件，这样就实现了多国语言功能，十分感谢~

**Comment by crazyandcoder** [comment]
@PeterXiaosa  厉害

**Comment by crazyandcoder** [comment]
@PeterXiaosa  最新版可以借鉴加载哪种json文件的方式，可以参考一下。

**Comment by PeterXiaosa** [comment]
我已经解决了之前的那个问题 我也会去看看您说的 谢谢~

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
