### ISSUE TITLE
能改 “取消” “确定” 这两个按钮的颜色吗

### ISSUE THREAD

**Issue by BestSingerInSiHui** [crazyandcoder/citypicker#4]
现在好像是拿app主题的颜色，我能手动改这个颜色吗

**Comment by crazyandcoder** [comment]
目前暂未提供相关属性，有两种办法可以解决:

1. 自己修改源码，修改颜色

2. 等我修改，然后发布

**Comment by BestSingerInSiHui** [comment]
好吧

**Comment by BestSingerInSiHui** [comment]
还有就是希望有一个方法，让我第一次show()的时候，上面的城市是我所想要的，

例如我在广州 海珠区， 我想在show()之后，看到  广东省  广州市  海珠区

**Comment by crazyandcoder** [comment]
以前也考虑过这个方法，这里面会涉及到定位的使用，而现在定位一般都是使用的高德地图或者百度地图之类的，如果我这边使用了第三方的jar包的话，如果你们自己项目又添加jar包，android studio编译时会提示失败的。

**Comment by BestSingerInSiHui** [comment]
那如果是你不用地图类的，你只开一个方法让我设初始城市，我在自己的项目用地图获取城市，然后在builder的时候把他设进去

**Comment by crazyandcoder** [comment]
哎呦，不错，这倒是个好主意，等我空下来实现一下，多谢啦~

**Comment by crazyandcoder** [comment]
已添加默认省市区设置，同时添加修改字体颜色的设置，请查看最新版本
