### ISSUE TITLE
项目中地址Json数据不是最新的啊？  襄樊改名襄阳了 ，建议更新下。

### ISSUE THREAD

**Issue by zhouyaxu1** [crazyandcoder/citypicker#43]
项目中地址Json数据不是最新的啊？  襄樊改名襄阳了 ，建议更新下。

**Comment by crazyandcoder** [comment]
@zhouyaxu1 谢谢建议，正在使用较新的数据，包含城市code，正在优化重构，请耐心等待发布最新版本
