### ISSUE TITLE
CityPickerView中解析省市区的XML数据

### ISSUE THREAD

**Issue by Martin3Young** [crazyandcoder/citypicker#46]
String cityJson = utils.getJson(context, "city_20170724.json"); 
utils报错。运行失败

**Comment by crazyandcoder** [comment]
log贴出来看看呢

**Comment by Martin3Young** [comment]
Error:(660, 27) 错误: 找不到符号
符号:   变量 utils
位置: 类 CityPickerView
Error:Execution failed for task ':citypickerview:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by crazyandcoder** [comment]
@Martin3Young   刚修复了一个问题，你使用最新版本2.0.1试试

**Comment by Martin3Young** [comment]
city_20170724这个文件里面的CityPickerView类，没有定义utils。

**Comment by crazyandcoder** [comment]
@Martin3Young   你是依赖我的module？utils类上传了

**Comment by Martin3Young** [comment]
没，我就把demo拉下来想运行下，然后就报错

**Comment by crazyandcoder** [comment]
@Martin3Young   因为我的代码没有及时提交上去，现在都上传了，应该能运行了

**Comment by Martin3Young** [comment]
好的，辛苦了

**Comment by crazyandcoder** [comment]
@Martin3Young 多谢使用！
