### ISSUE TITLE
我怎么感觉弹出的城市三级联动是一个activity？

### ISSUE THREAD

**Issue by xlc1540697096** [crazyandcoder/citypicker#48]
感觉很别扭，没有必要这样做吧。

**Comment by crazyandcoder** [comment]
@xlc1540697096  有时候人的感觉是有问题的，眼见不一定为实何况是感觉？fucking the resource code才是真的。

**Comment by xlc1540697096** [comment]
popupwindow 设为match_parent 了。我还是太年轻。
