### ISSUE TITLE
台湾的不全

### ISSUE THREAD

**Issue by awu515** [crazyandcoder/citypicker#50]
如题。。能否更新下

**Comment by crazyandcoder** [comment]
原始数据 香港澳门台湾数据都不全，我花了半个小时把香港和澳门的数据搞完了，再看台湾的数据，光区就有上百个，很好时间，所以就直接显示市，不显示区了，太特么的费时费力

**Comment by crazyandcoder** [comment]
@awu515  已修复台湾数据问题

**Comment by CaptainBlackCat** [comment]
还是不够优化啊，港澳台显示不好

**Comment by crazyandcoder** [comment]
@CaptainBlackCat 怎么个显示不好？你们用到港澳台的数据？

**Comment by CaptainBlackCat** [comment]
有好多数组下标越界异常

**Comment by crazyandcoder** [comment]
能提供具体越界的省市区吗？
