### ISSUE TITLE
加载速度有点太慢，点击不能立马反应，不是很流畅呢

### ISSUE THREAD

**Issue by wenzhihao123** [crazyandcoder/citypicker#55]

**Comment by crazyandcoder** [comment]
感谢使用，这是因为加载的时候需要解析json城市数据，数据量很大，导致时间很长，正在优化。。。敬请期待

**Comment by zhouyaxu1** [comment]
加载速度是有点慢了。特别是一个手机性能不怎么样的手机，那个速度真的是很酸爽。  希望可以优化下。

**Comment by crazyandcoder** [comment]
感谢提醒，正在优化中。。。

**Comment by sg552** [comment]
#### 注意：如果仅仅用来选择　省市区，不必进行地理位置，邮编，拼音匹配等操作的话，可以在源代码中，使用更加精简的
JSON文件 (见 src/main/assets/simple_cities.json )来替代．

JSON　文件格式：(注意，该文件的内容建议自行生成，因为不同公司的项目，
对于直辖市的处理手法是不一样的）

```
[
  {
    "name":"直辖市",
    "cityList":[
      {   
        "name":"北京",
        "cityList":[
          {   
            "name":"东城区" 
          },  
          {   
            "name":"西城区" 
          }   
        ]   
      }   
    ]   
  ｝  
  // 第二个省份．．．
］
```

同时，修改对应的 文件（ProvinceBean, CityBean, DistrictBean),
只保留name, cityList 这两个必要的属性的　getter/setter, 就可以了．
