### ISSUE TITLE
你的gradle依赖的库跟你现在的源码不一样吧，该更新了，还有打relase包的时候直接报错

### ISSUE THREAD

**Issue by Code6666** [crazyandcoder/citypicker#59]
你的gradle依赖的库跟你现在的源码不一样，该更新了，
还有打relase的安装包，装上点击弹出轮动选择器直接报空指针了

**Comment by crazyandcoder** [comment]
@Code6666  一般情况下，有新改动都会提交新版本，并且发布出来，如果发现gradle的版本号跟源码不一致的话，请按照readMe中的版本号进行使用，因为源码中的版本号有可能是我进行测试用的，请务必使用公布出来的版本号！！！
