### ISSUE TITLE
二级联动

### ISSUE THREAD

**Issue by mercuryglory** [crazyandcoder/citypicker#6]
你好,感谢分享.
我想实现一个只要省市的二级联动效果,不知道您这边要怎么设置?

**Comment by crazyandcoder** [comment]
这个到没有考虑到，这两天我添加一下这个功能，然后通知你！

**Comment by crazyandcoder** [comment]
已经实现两级联动功能，设置属性onlyShowProvinceAndCity(true) //显示省市两级联动即可，请查看最新版本实现。

**Comment by mercuryglory** [comment]
3q~~~

**Comment by crazyandcoder** [comment]
共同进步，嘿嘿
