### ISSUE TITLE
数据加载问题

### ISSUE THREAD

**Issue by morningchu** [crazyandcoder/citypicker#64]
作者辛苦了，请问一下，如果设置为滚轮模式，可以加载服务器返回的json数据吗？省市区分开，比如：初始加载省返回的json，选择省级后我们请求市级数据然后再加载市级json,区也依次，这样可以吗？^_^

**Comment by crazyandcoder** [comment]
@morningchu 感谢使用！

因为我不知道你们的服务器返回的json数据的格式，所以无法设置。只要按照一定的格式来，才能解析，另外可以依次加载数据。代码里面封装有基础的滚轮控件的使用法，你可以用这个控件加载你们服务器的数据，进行定制就好了，我这个只是满足一些基础，简单的地址选择器而已。
