### ISSUE TITLE
现在最新版本为什么选择器的回调都没有了

### ISSUE THREAD

**Issue by OnClickListener2048** [crazyandcoder/citypicker#69]
现在什么都无法选中了   请紧急修复一下

**Comment by crazyandcoder** [comment]
@OnClickListener2048 

//监听方法，获取选择结果，根据你选择的显示类别，覆盖对应的返回结果，如果获取结果失败，请检查选择的类型跟结果返回方法是否对应！！！！
cityPicker.setOnCityItemClickListener(new CityPickerView.OnCityItemClickListener() {

					//当只选择省份时，需要覆盖此方法，从该方法中获取省份结果
                    @Override
                    public void onSelected(ProvinceBean province) {
                    
			        //ProvinceBean 省份信息
			        
                    }

					//当只选择省市两级时，需要覆盖此方法，从该方法中获取省份和城市结果
					@Override
                    public void onSelected(ProvinceBean province, CityBean city ) {
                    
			        //ProvinceBean 省份信息
			        //CityBean     城市信息
			        
                    }

					//当只选择省市区三级时，需要覆盖此方法，从该方法中获取省市区三级联动结果
					@Override
                    public void onSelected(ProvinceBean province, CityBean city, DistrictBean district) {
                    
			        //ProvinceBean 省份信息
			        //CityBean     城市信息
			        //DistrictBean 区县信息
			        
                    }

                    @Override
                    public void onCancel() {

                    }
                });

**Comment by crazyandcoder** [comment]
问题应该是你没注意看使用说明，选择省市区的type需要跟返回结果对应！！！

第二种方法看最新版本，修改了返回结果的数据结构，认真看说明！
