### ISSUE TITLE
请求更新数据

### ISSUE THREAD

**Issue by wl386123298** [crazyandcoder/citypicker#7]
更新数据如下：
安徽--合肥--(蜀山区，瑶海区，庐阳区，高新区，新站区，滨湖新区，包河区，肥东县，肥西县，长丰县)
安徽--六安--去除寿县
安徽--淮南---加上寿县

希望更新！

**Comment by crazyandcoder** [comment]
请问你这个数据是从哪里来的？我在百度上面查了一下关于合肥的区县，跟你提供的有些区别。

**Comment by wl386123298** [comment]
我本身就是合肥人，刚查了下，合肥还有庐江县和巢湖市
关于寿县的改变因为是才批复下来，所以网上说的可能都不准确！

**Comment by crazyandcoder** [comment]
你能提供数据地址吗？我在维基百科上面查看了一下，合肥包括：市辖区：瑶海区、庐阳区、蜀山区、包河区，县：长丰县、肥东县、肥西县、庐江县，县级市：巢湖市，此外，合肥市设立以下经济管理区，并赋予县级管理权限：合肥高新技术产业开发区（国家级）、合肥经济技术开发区（国家级）、新站综合开发试验区。综合一下就是你的：“合肥--(蜀山区，瑶海区，庐阳区，高新区，新站区，滨湖新区，包河区，肥东县，肥西县，长丰县)”？

**Comment by wl386123298** [comment]
是的，经济开发区隶属肥西管辖，合肥主城区就是4个，其他的都隶属这4个区管辖！所以我提供的数据包含了你上面说的！

**Comment by crazyandcoder** [comment]
嗯，好，我有空就更新一下最新数据，同时请关注结果。

**Comment by crazyandcoder** [comment]
城市数据已修复

**Comment by GhostGame** [comment]
城市数据最好以统计局的这个为准，如果能把统计局公布的编码也给提供进来就更好了
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/

**Comment by crazyandcoder** [comment]
谢谢提供这么好的信息！

已获取统计局最新的城市数据，抽空将它更新上去，并添加最新的城市id。
