### ISSUE TITLE
这边有一个需求就是 我一个页面里面有两个地方需要调用选择器  

### ISSUE THREAD

**Issue by OnClickListener2048** [crazyandcoder/citypicker#72]
这边有一个需求就是 我一个页面里面有两个地方需要调用选择器   但是两个地方的选择器  其中一个是两级联动 一个地方是三级联动   但是现在的来说是只能建造两个config然后再去new出citypicker  但是这样的问题就是 会加载两次数据  能否加入builder模式来解决这个问题呢  急求

**Comment by crazyandcoder** [comment]
请看最新的版本3.0.0使用说明
