### ISSUE TITLE
台湾、澳门、香港时崩溃的问题；2.12最新版本

### ISSUE THREAD

**Issue by xiaojianren1993** [crazyandcoder/citypicker#74]
希望大神及时修改。

**Comment by xiaojianren1993** [comment]
仿iso滚轮的

**Comment by crazyandcoder** [comment]
@xiaojianren1993   具体的操作流程是什么，选择的属性是什么？

**Comment by xiaojianren1993** [comment]
是我的错 粗心了，没有判断是否为空。但是发现了这个 打包或者真机运行出来的 这是Gson冲突？
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/gson/TypeAdapter;

**Comment by crazyandcoder** [comment]
@xiaojianren1993  不是，这个是包重复依赖的问题，可以参考一下这个解决方案试试。

http://blog.csdn.net/hyr83960944/article/details/41825087
