### ISSUE TITLE
能否增加个属性，可以控制显示或者隐藏台湾、香港、澳门这些地方

### ISSUE THREAD

**Issue by FishionMark** [crazyandcoder/citypicker#76]

**Comment by crazyandcoder** [comment]
为什么要隐藏这些地方，感觉很奇怪啊？

**Comment by FishionMark** [comment]
因为产品只做国内的，加上也行，不过得自己判断支不支持这些地区。但是如果有的产品经理要求不要这些，那么这个库就不好处理了吧？个人理解

**Comment by crazyandcoder** [comment]
@FishionMark   这个库主要是服务大众的，但是特别的需求还是不支持的，只有众需的时候，我才考虑添加上去。但是你可以自己dependence module的形式，来满足你的需求。提供个思路，就是在解析的时候，如果是你需要过滤掉的城市，直接跳过当前循环即可。以后如果很多人都有类似的需求，我会考虑通过添加属性的方式来满足这个需求。
