### ISSUE TITLE
加载速度太慢 导致页面卡顿  而且不能在子线程加载

### ISSUE THREAD

**Issue by OnClickListener2048** [crazyandcoder/citypicker#77]
能否给一个统一的异步加载方式？

**Comment by OnClickListener2048** [comment]
最好是在application中可以将数据全部异步加载进来  这样可以保证在无论哪个页面加载都不会重新加载数据json  而不是现在的 我在很多个页面加载时都要从新加载json地区数据

**Comment by crazyandcoder** [comment]
感谢建议，下个版本优该问题。

**Comment by crazyandcoder** [comment]
@OnClickListener2048  3.0.0版本已修改该问题，采用预先加载方式，提高加载效率！
