### ISSUE TITLE
省市区背景颜色可以更改嘛？

### ISSUE THREAD

**Issue by misterdai520** [crazyandcoder/citypicker#78]
省市区背景颜色最好也可以进行更改，如果方便的话能否增加个方法

**Comment by crazyandcoder** [comment]
收到，请耐心等待，下个版本增加该属性。

**Comment by misterdai520** [comment]
thinks

**Comment by misterdai520** [comment]
方便的话，上面的标题，取消和确定按钮的字体大小也能进行修改

**Comment by crazyandcoder** [comment]
@misterdai520 3.0.0版本已发布，增加你想要的属性，你看详细的使用说明。https://github.com/crazyandcoder/citypicker
