### ISSUE TITLE
遇到了bug...不知道什么原因 

### ISSUE THREAD

**Issue by k354250377** [crazyandcoder/citypicker#79]
![20171217_053102](https://user-images.githubusercontent.com/20323504/34074508-b6f24d38-e2eb-11e7-8680-8dbec8187212.jpg)
![20171217_053106](https://user-images.githubusercontent.com/20323504/34074509-b724c8f8-e2eb-11e7-9513-6afc4c3d7079.jpg)
这是啥情况......很蛋疼  还有json资源我可以使用我本地的么  我不需要全国的选择 只需要北京.....

**Comment by k354250377** [comment]
我用两个手机测试了  都是这样...
真是个奇怪的bug.....

**Comment by k354250377** [comment]
经过我的测试...好像2.0以下用旧版代码就可以完美显示北京 2.0.0之后的版本就够挂了......

**Comment by k354250377** [comment]
看在我折腾一宿的份上请睡醒了回答我一下啊

**Comment by k354250377** [comment]
我放弃了 我去用2.0.0吧......

**Comment by crazyandcoder** [comment]
不可以使用本地的数据
