### ISSUE TITLE
能否增加点属性

### ISSUE THREAD

**Issue by zjx19930911** [crazyandcoder/citypicker#8]
比如像阴影的颜色，现在这个太深了。。
还有确定取消按钮中间个选择地址的字，最好可以自定义。
还有确定取消背景的颜色，灰色不好看。。 ^_^

**Comment by crazyandcoder** [comment]
可以呀，等这段时间空下来统一处理哈

**Comment by crazyandcoder** [comment]
发布新包，增加修改标题属性和设置标题背景颜色
