### ISSUE TITLE
能设置底部弹窗的Margin吗

### ISSUE THREAD

**Issue by Adaclass** [crazyandcoder/citypicker#86]
如果暴露出Api来设置PopWindow的Margin就好了：）。

**Comment by crazyandcoder** [comment]
后期可以考虑考虑，这需求你还是第一个提。

**Comment by Adaclass** [comment]
我项目遇到了。。。只有把你的库弄到项目里查看源代码好久才设置好了o(╥﹏╥)o

**Comment by crazyandcoder** [comment]
哈哈哈，如果需要特别的需求只能依赖module改源码的，靠开放API的方式不大合适的，自己动手丰衣足食！
