### ISSUE TITLE
河南省没有济源市

### ISSUE THREAD

**Issue by Vancons** [crazyandcoder/citypicker#88]
济源市 在焦作市里面

**Comment by Vancons** [comment]
济源市 在焦作市里面

**Comment by crazyandcoder** [comment]
请提供使用的是哪个版本

**Comment by Vancons** [comment]
3.0.0

**Comment by crazyandcoder** [comment]
@Vancons   3.0.0以上版本的数据源都是用的simple_cities_pro_city_dis.json 文件，其他的没用到，我没把他们删除。

**Comment by Vancons** [comment]
@crazyandcoder  我修改一下试试， 还有就是 picker 的背景现在好像也不能自己设置吧？没找到方法

**Comment by crazyandcoder** [comment]
背景？你指的是什么？透明度么？

**Comment by Vancons** [comment]
弹出框的背景颜色，现在已经找到方法了。大神，还有就是济源市在焦作市的二级里面，你更新3.0.1的时候没有修改。我是依赖源码修改的，使用没问题了。感谢分享
