### ISSUE TITLE
issue提问规则

### ISSUE THREAD

**Issue by crazyandcoder** [crazyandcoder/citypicker#89]
请issue之前先看看[closed](https://github.com/crazyandcoder/citypicker/issues?q=is%3Aissue+is%3Aclosed)里面有没有类似的issue，这样能提高你的解决问题的效率！

另外，如果不存在类似的issue可进入citypicker专属群进行提问。[citypicker专属群](https://github.com/crazyandcoder/citypicker/issues/95)

1、请添加使用版本号
2、描述现象以及期望结果。

本issue只是作为说明使用，请大伙提issue，另开页面，不要在该页面下面提issue，谢谢合作。

**Comment by Adaclass** [comment]
大神，你好：）。我用的CityPicker版本是3.0的。用的不错，Boss看了都说好，就是界面有点丑了。所以我想问下，那两道黑的分割线和wheelView的渐变色能改吗？我好像找到了渐变色，是数组。。不过还是想问一下

**Comment by crazyandcoder** [comment]
@Adaclass 感谢使用并提出意见， 可以修改的，但是没有提供修改的方法，下个版本优化一下然后我放出来供大伙使用。

**Comment by hushibin** [comment]
大神，我想问下，选择上海的时候。市区为啥是重复的。里面应该就只有一个上海，怎么还有上海崇明县呢。然后就是重复这两个数据。希望改下。

**Comment by crazyandcoder** [comment]
@hushibin   感谢提出这个问题，可能是数据比较老了，下个版本会修正上海的数据，谢谢！

**Comment by hushibin** [comment]
大神，还有个问题就是，区里面为啥还有县。大神希望快点出下个版本。正在使用中。谢谢。

**Comment by crazyandcoder** [comment]
@hushibin  有的地方，区和县属于同等级别的，这就得看国家怎么定义的。可以去看看国家统计局的数据。

**Comment by hushibin** [comment]
@crazyandcoder 谢谢。

**Comment by lamandys** [comment]
在城市列表中是没有地级市的么，比如阳春市，在城市列表找不到，其他两个都有

**Comment by crazyandcoder** [comment]
@lamandys 没有第三级地区，只能显示二级市

**Comment by qianggezaicunjin** [comment]
大神好，这个库非常棒。但是最近由于数据源我需要修改。所以不能使用系统自带的那个地区数据源，想问下这个问题应该怎么解决呢

**Comment by crazyandcoder** [comment]
1.按照库asset目录下面的本地城市数据json格式替换一下

2.用其他的控件库试试

**Comment by riseLishan** [comment]
想问下json文件的地址是什么时候的。谢谢

**Comment by crazyandcoder** [comment]
2016年的
