### ISSUE TITLE
建议作者提供更多设置样式的方法

### ISSUE THREAD

**Issue by lishide** [crazyandcoder/citypicker#9]
建议提供设置标题、“确定”、“取消”按键的文字颜色、大小等属性的方法，更加方便使用。

**Comment by crazyandcoder** [comment]
v0.4.0版本已经提供设置“确定和取消”文字颜色的属性

**Comment by Ericlsd** [comment]
还有标题的颜色，就是“选择地区”的颜色，另外提供int类型的颜色赋值方式。
