### ISSUE TITLE
单列表城市选择后有几个条目返回数据为空

### ISSUE THREAD

**Issue by morningchu** [crazyandcoder/citypicker#90]
兄弟，有bug，单列表城市，从阿坝藏族到阿勒泰 这五个城市选择后返回数据是空的

**Comment by morningchu** [comment]
厉害了，不止这五个，下面还有，关键是间接的，间接的，哈哈，单列表的所有城市，选择后有的返回是空数据，你看下吧，

**Comment by crazyandcoder** [comment]
我看了一下，都会有城市数据的。你的有可能是数据没有解析成功之类的。
