### ISSUE TITLE
关于版本升级问题

### ISSUE THREAD

**Issue by OnClickListener2048** [crazyandcoder/citypicker#91]
我之前用的是 2.01版本 现在突然升级到3.01  版本变动太大 而且项目里面修改太复杂  希望能出一个版本兼容3.0之前的版本 并且可以异步加载数据。作者辛苦了 谢谢

**Comment by crazyandcoder** [comment]
好蛋疼，兼容以前的版本的异步加载很复杂。。。

**Comment by crazyandcoder** [comment]
@OnClickListener2048  大兄弟，我看了一下issues，我发现至少有1/10的问题都是你提的。感谢使用，小母牛下山，牛逼朝天了。
