### ISSUE TITLE
2.01版本 关于cityconfig设置默认省市

### ISSUE THREAD

**Issue by OnClickListener2048** [crazyandcoder/citypicker#92]
现在的设置默认省市是只能够设置省市区三项后才能设置默认的省市  但是在全国范围内来讲 省市区应该是没有同名的 所以应该支持只数据一个 市的名字或者区的名字来设置默认省市区选项

**Comment by crazyandcoder** [comment]
@OnClickListener2048  https://zhidao.baidu.com/question/690291318200407604.html
