### ISSUE TITLE
版本3.01.无论调用默认的方式，还是自定义的方式，弹出来的窗口都只有选择地区那一行

### ISSUE THREAD

**Issue by He-Jin** [crazyandcoder/citypicker#93]
版本3.01.无论调用默认的方式，还是自定义的方式，弹出来的窗口都只有标题 选择地区那一行，其他界面隐藏在底部了   ---------在项目主帮助下已解决，加载时候加载错成三级列表，调用的是IOS轮询，造成只弹出一点点

**Comment by crazyandcoder** [comment]
需要先解析本地城市数据。
