### ISSUE TITLE
citypicker专属群：417846442

### ISSUE THREAD

**Issue by crazyandcoder** [crazyandcoder/citypicker#95]
#### **CityPicker 城市选择器专属QQ群，欢迎加入！**

![](http://img.blog.csdn.net/20180117170913580?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvbGlqaV94Yw==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

**Comment by crazyandcoder** [comment]
欢迎各位加入，在群里可以提出关于citypicker任何问题，当然也可以提出其他问题，互相学习，共同进步。

**Comment by Glorylan** [comment]
自定义布局文字我想要那种选中是蓝色，未选中默认色的，用selector 定制没有焦点时，选中字体时，非触摸焦点并单击时的颜色  只有 没有焦点的时候生效 并且所有都是这种效果  其他没有生效，要如何解决？

**Comment by crazyandcoder** [comment]
修改源码

**Comment by 1825273284** [comment]
RN可以用不？

**Comment by azz1123** [comment]
可以用web端吗 ？效果是什么样的呢

**Comment by wengeqiua** [comment]
有没有只显示港澳台的方法，或者怎么设置自己的数据源？

**Comment by ziuker** [comment]
遇到些问题，怎么进入qq群

**Comment by crazyandcoder** [comment]
@ziuker  qq群：417846442
