### ISSUE TITLE
内存泄露     CityPickerView.getInstance().setConfig(new CityConfig.Builder(this).build();

### ISSUE THREAD

**Issue by LouisShark** [crazyandcoder/citypicker#96]
如题 单例的CityPickerView传进去一个activity的上下文会导致内存泄露

**Comment by LouisShark** [comment]
@crazyandcoder

**Comment by crazyandcoder** [comment]
感谢使用并提出问题，把log贴出来看看呢！

**Comment by LouisShark** [comment]
emmr 单例长生命周期的cityPicker引用短生命周期context(activity)肯定会泄露的吧

**Comment by LouisShark** [comment]
![image](https://user-images.githubusercontent.com/18005609/35028803-d72859b6-fb92-11e7-9a10-e36deaadec0c.png)

**Comment by crazyandcoder** [comment]
@LouisShark   恩，非常感谢提出这个问题。虽然用LeakCanary检查了一下没有出现内存泄漏，但是理论上还是会出现的，下个版本会修复该问题。

**Comment by crazyandcoder** [comment]
@LouisShark  已修复该问题，请使用最新版本
