### ISSUE TITLE
关于OnCityItemClickListener失效的问题

### ISSUE THREAD

**Issue by ITGrocery** [crazyandcoder/citypicker#97]
我在ViewPager中的多个Fragment中调用citypicker，会出现确定按钮失效的问题，应该是citypicker使用单利模式的原因，前面页面设置的OnCityItemClickListener会被后面的页面覆盖掉。目前我是利用Fragment的生命周期来重新设置OnCityItemClickListener的，每次Fragment置顶到屏幕上面时就重新设置一下OnCityItemClickListener，如果能简单点处理这个问题就好了。

**Comment by crazyandcoder** [comment]
使用最新版本试试还存不存在这个问题

**Comment by ITGrocery** [comment]
我用的就是最新版
